FROM  jenkins/jenkins:latest
ENV NODE_VERSION="v12.9.1"
ENV MAVEN_VERSION="3.8.6"
USER  root
COPY  plugins.txt  /usr/local/bin/
COPY  sources.list /usr/local/bin/
#RUN  /usr/local/bin/install-plugins.sh ansicolor
#RUN  /usr/local/bin/install-plugins.sh greenballs
#RUN  /usr/local/bin/install-plugins.sh kubernetes
ENV  MAVEN_HOME=/usr/local/maven/apache-maven-$MAVEN_VERSION
ENV  PATH=${MAVEN_HOME}/bin:${PATH}
ENV  NODE_HOME=/usr/local/node
ENV  PATH=$NODE_HOME/bin:$PATH
RUN  apt-get update && apt-get install -y wget apt-utils vim zip sshpass
RUN  cd /usr/local/bin/ && \
     ./install-plugins.sh < plugins.txt || true   && \
     mkdir /opt/install && cd /opt/install &&\
     wget https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz && \
     mkdir -pv /usr/local/maven/  && \
     tar xzvf  apache-maven-$MAVEN_VERSION-bin.tar.gz  -C /usr/local/maven/  && \
     wget https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz  && \
     tar  xzvf  node-$NODE_VERSION-linux-x64.tar.gz  -C /usr/local/  && \
     cd /usr/local/  && \
     mv node-$NODE_VERSION-linux-x64/ node  && \
     export   NODE_HOME=/usr/local/node  && \
     export   PATH=$NODE_HOME/bin:$PATH  && \
     /usr/local/node/bin/npm install -g cnpm --registry=https://registry.npm.taobao.org  && \
     /usr/local/node/bin/npm config set registry https://registry.npm.taobao.org  && \
     /usr/local/node/bin/npm  update  && \
     #cnpm update  && \
     cd /opt && \
     rm -rfv /opt/install/* && apt-get clean && rm -rf /var/lib/apt/lists/*
